services:
  bcra:
    container_name: bcra
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true